### PR TITLE
fix(tests): Fix race conditions when multiple agents require user interaction

### LINKED ISSUE #97: Investigate CI timeouts
CI jobs "Build & Publish" seem to have started to timeout recently. Example:

https://github.com/dremio/iceberg-auth-manager/actions/runs/16292853320/job/46006786923

The task that is timing out is `:authmgr-oauth2-core:test`. It seems that the test that "hangs" is `TokenExchangeFlowTest`. 

The issue does not manifest locally, only in CI. Looks like a deadlock.

### PR DESCRIPTION
**Pull request by adutra**
Fixes #97.

This change fixes various race conditions, mostly in test code:

* In the user emulator classes;
* In expectation classes (for Authorization Code and Device Code);
* In flow classes (for Authorization Code and Device Code).

One of the reported race conditions is #97, which is due to 2 concurrent agents asking for authentication in parallel.

The `UserEmulator` API was completely redesigned (and considerably simplified).

The affected expectation classes were refactored to remove internal fields that were causing race conditions. These were replaced with maps that keep track of all the in-flight requests.

The affected flow classes now synchronize on the console PrintStream before printing messages, in order to avoid garbled messages when two agents attempt to print at the same time.

### CODE REVIEW

File: oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/user/AuthorizationCodeUserFlow.java [hunk 1]
```diff
@@ -29,83 +31,53 @@
...
     }
   }
 
   /** Emulate browser being redirected to callback URL. */
   private void invokeCallbackUrl(URI callbackUrl) throws Exception {
     LOGGER.debug("Opening callback URL...");
     assertThat(callbackUrl).hasParameter("code").hasParameter("state");
-    if (authorizationCodeOverride != null) {
+    boolean useWrongConde = getUserBehavior().isEmulateFailure();
+    if (useWrongConde) {
```
Comment (dimas-b) [inline oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/user/AuthorizationCodeUserFlow.java:67]: nit: Conde -> Code?
