### PR TITLE
fix(crypto): Avoid using legacy RSA algorithms

### LINKED ISSUE #234: Revisit default values for encryption algorithms
Currently the project defaults to RS256 for JWT client auth.

The project should instead default to PS256, maybe even ES256 - just to not give a false impression of "legacy RSA is still safe".

It should also emit warnings when legacy RSA algorithms (RS*) are being selected.

### PR DESCRIPTION
**Pull request by adutra**
Fixes #234.

This change moves the default RSA algorithm from RS512 to PS512, thus using RSA-PSS by default rather than "legacy" RSA.

It also fixes a bug where the default HMAC algorithm was actually HS256 instead of HS512.

### CODE REVIEW

File: oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/AbstractFlow.java [hunk 1]
```diff
@@ -199,7 +199,7 @@ ClientAuthentication createClientAuthentication() {
     } else if (method.equals(CLIENT_SECRET_JWT)) {
       JWTAssertionDetails details = createJwtAssertionDetails(tokenEndpoint);
       JWSAlgorithm algorithm =
-          getConfig().getJwtClientAuthConfig().getAlgorithm().orElse(JWSAlgorithm.HS256);
+          getConfig().getJwtClientAuthConfig().getAlgorithm().orElse(JWSAlgorithm.HS512);
```
Comment (adutra) [inline oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/AbstractFlow.java:202]: This was actually a bug: the intent was to default to `HS512` since the beginning, but it was defaulting to `HS256` instead.

File: docs/configuration.md [hunk 2]
```diff
@@ -440,9 +440,11 @@ The expiration time of the client assertion JWT. Optional. The default is 5 minu
 
 ### `rest.auth.oauth2.client-auth.jwt.algorithm`
 
-The signing algorithm to use for the client assertion JWT. Optional. The default is `HS512` if the authentication method is `client_secret_jwt`, or `RS512` if the authentication method is `private_key_jwt`.
+The signing algorithm to use for the client assertion JWT. Optional. The default is `HS512` if the authentication method is `client_secret_jwt`, or `PS512` if the authentication method is `private_key_jwt`.
```
Comment (snazy) [inline docs/configuration.md:443]: Is there a changelog in the project?

File: oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/config/JwtClientAuthConfig.java [hunk 3]
```diff
@@ -136,25 +140,26 @@ public interface JwtClientAuthConfig {
   default void validate() {
     ConfigValidator validator = new ConfigValidator();
     if (getAlgorithm().isPresent()) {
```
Comment (snazy) [inline oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/config/JwtClientAuthConfig.java:142]: Super-nit: `getAlgorithm().ifPresent(algorithm -> {`

File: oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/junit/KeycloakExtension.java [hunk 4]
```diff
@@ -62,7 +63,7 @@ public class KeycloakExtension extends TestEnvironmentExtension
 
   // Client3 is used for client_secret_jwt authentication
   public static final String CLIENT_ID3 = "Client3";
-  public static final String CLIENT_SECRET3 = Strings.repeat("S3CR3T", 10);
+  public static final String CLIENT_SECRET3 = generateSecret();
```
Comment (snazy) [inline oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/junit/KeycloakExtension.java:66]: Hidden gem?

**Review by snazy — APPROVED** [review]

File: docs/configuration.md (hunk 2 above)
Comment (adutra) [reply docs/configuration.md:443]: No, it's generated during release. We currently don't have a way to advertise these changes :-(

File: oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/junit/KeycloakExtension.java (hunk 4 above)
Comment (adutra) [reply oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/junit/KeycloakExtension.java:66]: I had to change this because `Strings.repeat("S3CR3T", 10)` is slightly too short for `HS512`. I could have done `Strings.repeat("S3CR3T", 11)` – but feels clumsy.
